In [1]:
!pip install numpy==2.0.2
!pip install pandas==2.2.2
!pip install tensorflow_cpu==2.18.0

Collecting numpy==2.0.2
  Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 117.8 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.0.2
Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2024.2)
Collecting tzdata>=2022.7 (from pandas==2.2.2)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 105.4 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-2.2.2 tzdata-2025.3
Collecting tensorflow_cpu==2.18.0
  Downloading tensorflow_cpu-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting absl-py>=1.0.0 (from tensorflow_cpu==2.18.0)
  Downloading absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow_cpu==2.18.0)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow_cpu==2.18.0)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow_cpu==2.18.0)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google-pasta>=0.1.1 (from tensorflow_cpu==2.18.0)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow_cpu==2.18.0)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow_cpu==2.18.0)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (24.2)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 (from tensorflow_cpu==2.18.0)
  Downloading protobuf-5.29.5-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.32.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (75.8.0)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow_cpu==2.18.0)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (4.12.2)
Collecting wrapt>=1.11.0 (from tensorflow_cpu==2.18.0)
  Downloading wrapt-2.0.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (9.0 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow_cpu==2.18.0)
  Downloading grpcio-1.76.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.7 kB)
Collecting tensorboard<2.19,>=2.18 (from tensorflow_cpu==2.18.0)
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting keras>=3.5.0 (from tensorflow_cpu==2.18.0)
  Downloading keras-3.13.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.0.2)
Collecting h5py>=3.11.0 (from tensorflow_cpu==2.18.0)
  Downloading h5py-3.15.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting ml-dtypes<0.5.0,>=0.4.0 (from tensorflow_cpu==2.18.0)
  Downloading ml_dtypes-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow_cpu==2.18.0) (0.45.1)
Collecting rich (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading optree-0.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (34 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2024.12.14)
Collecting markdown>=2.6.8 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading markdown-3.10-py3-none-any.whl.metadata (5.1 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading werkzeug-3.1.5-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: markupsafe>=2.1.1 in /opt/conda/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.0.2)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (2.19.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow_cpu-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (230.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.3/230.3 MB 47.0 MB/s eta 0:00:0000:0100:01
Downloading absl_py-2.3.1-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading grpcio-1.76.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 83.1 MB/s eta 0:00:00
Downloading h5py-3.15.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 47.2 MB/s eta 0:00:00
Downloading keras-3.13.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 47.7 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 49.2 MB/s eta 0:00:00:00:01
Downloading ml_dtypes-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 52.9 MB/s eta 0:00:00
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading protobuf-5.29.5-cp38-abi3-manylinux2014_x86_64.whl (319 kB)
Downloading tensorboard-2.18.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 60.3 MB/s eta 0:00:00
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading wrapt-2.0.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (121 kB)
Downloading markdown-3.10-py3-none-any.whl (107 kB)
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 54.9 MB/s eta 0:00:00
Downloading werkzeug-3.1.5-py3-none-any.whl (225 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (408 kB)
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, libclang, flatbuffers, wrapt, werkzeug, termcolor, tensorboard-data-server, protobuf, optree, opt-einsum, ml-dtypes, mdurl, markdown, h5py, grpcio, google-pasta, gast, astunparse, absl-py, tensorboard, markdown-it-py, rich, keras, tensorflow_cpu
Successfully installed absl-py-2.3.1 astunparse-1.6.3 flatbuffers-25.12.19 gast-0.7.0 google-pasta-0.2.0 grpcio-1.76.0 h5py-3.15.1 keras-3.13.0 libclang-18.1.1 markdown-3.10 markdown-it-py-4.0.0 mdurl-0.1.2 ml-dtypes-0.4.1 namex-0.1.0 opt-einsum-3.4.0 optree-0.18.0 protobuf-5.29.5 rich-14.2.0 tensorboard-2.18.0 tensorboard-data-server-0.7.2 tensorflow_cpu-2.18.0 termcolor-3.3.0 werkzeug-3.1.5 wrapt-2.0.1

In [4]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [5]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

## Download and Clean the Data Set

In [6]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

#### Let's check how many data points we have

In [5]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

In [6]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [7]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The data looks very clean and is ready to be used to build our model.

#### Split data into predictors and target

In [8]:
concrete_data_columns = concrete_data.columns

In [10]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength']

In [11]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [12]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [13]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()  #standardisation
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Let's save the number of predictors to *n_cols* since we will need this number when building our network.

In [15]:
n_cols = predictors_norm.shape[1] # number of predictors

##  Import Keras Packages

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

In [17]:
def regression_model():
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

## Train and Test the Network

In [19]:
model = regression_model()

Next, we will train and test the model at the same time using the *fit* method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

In [20]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - 52ms/step - loss: 1671.0187 - val_loss: 1155.9882
Epoch 2/100
23/23 - 0s - 8ms/step - loss: 1550.6523 - val_loss: 1044.1299
Epoch 3/100
23/23 - 0s - 8ms/step - loss: 1364.5211 - val_loss: 872.4253
Epoch 4/100
23/23 - 0s - 8ms/step - loss: 1089.8799 - val_loss: 647.8237
Epoch 5/100
23/23 - 0s - 7ms/step - loss: 759.7896 - val_loss: 412.9998
Epoch 6/100
23/23 - 0s - 7ms/step - loss: 465.2487 - val_loss: 242.9139
Epoch 7/100
23/23 - 0s - 7ms/step - loss: 293.1345 - val_loss: 170.1865
Epoch 8/100
23/23 - 0s - 7ms/step - loss: 235.2935 - val_loss: 153.0464
Epoch 9/100
23/23 - 0s - 7ms/step - loss: 213.3624 - val_loss: 155.5898
Epoch 10/100
23/23 - 0s - 7ms/step - loss: 201.2831 - val_loss: 152.9227
Epoch 11/100
23/23 - 0s - 7ms/step - loss: 191.8204 - val_loss: 151.2292
Epoch 12/100
23/23 - 0s - 7ms/step - loss: 185.3587 - val_loss: 147.6896
Epoch 13/100
23/23 - 0s - 7ms/step - loss: 179.6679 - val_loss: 147.8931
Epoch 14/100
23/23 - 0s - 6ms/step - loss: 175.3809 - val_loss: 145.4088
Epoch 15/100
23/23 - 0s - 7ms/step - loss: 171.7766 - val_loss: 145.6825
Epoch 16/100
23/23 - 0s - 6ms/step - loss: 167.4459 - val_loss: 144.5317
Epoch 17/100
23/23 - 0s - 7ms/step - loss: 164.1392 - val_loss: 142.5084
Epoch 18/100
23/23 - 0s - 7ms/step - loss: 161.2148 - val_loss: 141.2307
Epoch 19/100
23/23 - 0s - 7ms/step - loss: 158.5736 - val_loss: 139.7087
Epoch 20/100
23/23 - 0s - 7ms/step - loss: 156.3186 - val_loss: 138.8060
Epoch 21/100
23/23 - 0s - 7ms/step - loss: 154.1882 - val_loss: 139.4156
Epoch 22/100
23/23 - 0s - 7ms/step - loss: 151.5318 - val_loss: 137.0817
Epoch 23/100
23/23 - 0s - 6ms/step - loss: 149.6075 - val_loss: 136.1299
Epoch 24/100
23/23 - 0s - 7ms/step - loss: 147.8475 - val_loss: 135.3280
Epoch 25/100
23/23 - 0s - 7ms/step - loss: 146.0910 - val_loss: 137.2520
Epoch 26/100
23/23 - 0s - 7ms/step - loss: 144.1684 - val_loss: 136.2312
Epoch 27/100
23/23 - 0s - 7ms/step - loss: 142.9130 - val_loss: 133.6882
Epoch 28/100
23/23 - 0s - 6ms/step - loss: 141.3362 - val_loss: 133.4522
Epoch 29/100
23/23 - 0s - 6ms/step - loss: 139.7559 - val_loss: 131.5005
Epoch 30/100
23/23 - 0s - 6ms/step - loss: 138.8958 - val_loss: 131.8210
Epoch 31/100
23/23 - 0s - 6ms/step - loss: 137.1585 - val_loss: 131.8013
Epoch 32/100
23/23 - 0s - 7ms/step - loss: 136.0750 - val_loss: 129.2766
Epoch 33/100
23/23 - 0s - 6ms/step - loss: 135.2868 - val_loss: 131.1066
Epoch 34/100
23/23 - 0s - 7ms/step - loss: 133.2984 - val_loss: 129.4418
Epoch 35/100
23/23 - 0s - 6ms/step - loss: 132.0472 - val_loss: 128.5682
Epoch 36/100
23/23 - 0s - 7ms/step - loss: 131.0217 - val_loss: 129.3568
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 129.6073 - val_loss: 128.6089
Epoch 38/100
23/23 - 0s - 7ms/step - loss: 128.5976 - val_loss: 128.0341
Epoch 39/100
23/23 - 0s - 6ms/step - loss: 127.4397 - val_loss: 128.0755
Epoch 40/100
23/23 - 0s - 7ms/step - loss: 125.9284 - val_loss: 126.8416
Epoch 41/100
23/23 - 0s - 7ms/step - loss: 125.2257 - val_loss: 127.2613
Epoch 42/100
23/23 - 0s - 6ms/step - loss: 123.5748 - val_loss: 125.7160
Epoch 43/100
23/23 - 0s - 7ms/step - loss: 122.0686 - val_loss: 126.7597
Epoch 44/100
23/23 - 0s - 7ms/step - loss: 120.6814 - val_loss: 125.7476
Epoch 45/100
23/23 - 0s - 7ms/step - loss: 119.6493 - val_loss: 126.7323
Epoch 46/100
23/23 - 0s - 6ms/step - loss: 118.2232 - val_loss: 123.7551
Epoch 47/100
23/23 - 0s - 7ms/step - loss: 116.5920 - val_loss: 123.3031
Epoch 48/100
23/23 - 0s - 7ms/step - loss: 115.0197 - val_loss: 124.5839
Epoch 49/100
23/23 - 0s - 7ms/step - loss: 113.0975 - val_loss: 122.3452
Epoch 50/100
23/23 - 0s - 7ms/step - loss: 112.1706 - val_loss: 121.8059
Epoch 51/100
23/23 - 0s - 7ms/step - loss: 109.9357 - val_loss: 119.3691
Epoch 52/100
23/23 - 0s - 7ms/step - loss: 108.0422 - val_loss: 120.9913
Epoch 53/100
23/23 - 0s - 7ms/step - loss: 105.8692 - val_loss: 120.8162
Epoch 54/100
23/23 - 0s - 7ms/step - loss: 104.7112 - val_loss: 119.7572
Epoch 55/100
23/23 - 0s - 11ms/step - loss: 101.5625 - val_loss: 117.6718
Epoch 56/100
23/23 - 0s - 11ms/step - loss: 98.8966 - val_loss: 115.8578
Epoch 57/100
23/23 - 0s - 7ms/step - loss: 96.5608 - val_loss: 113.1180
Epoch 58/100
23/23 - 0s - 7ms/step - loss: 93.8954 - val_loss: 112.9716
Epoch 59/100
23/23 - 0s - 7ms/step - loss: 90.7858 - val_loss: 112.2094
Epoch 60/100
23/23 - 0s - 7ms/step - loss: 87.6144 - val_loss: 111.2917
Epoch 61/100
23/23 - 0s - 8ms/step - loss: 84.9024 - val_loss: 107.7194
Epoch 62/100
23/23 - 0s - 7ms/step - loss: 81.2284 - val_loss: 106.6932
Epoch 63/100
23/23 - 0s - 7ms/step - loss: 77.6303 - val_loss: 103.2730
Epoch 64/100
23/23 - 0s - 7ms/step - loss: 74.5844 - val_loss: 102.1295
Epoch 65/100
23/23 - 0s - 6ms/step - loss: 71.3444 - val_loss: 100.0108
Epoch 66/100
23/23 - 0s - 7ms/step - loss: 68.1805 - val_loss: 97.0525
Epoch 67/100
23/23 - 0s - 7ms/step - loss: 65.5584 - val_loss: 98.5898
Epoch 68/100
23/23 - 0s - 8ms/step - loss: 63.2391 - val_loss: 94.2321
Epoch 69/100
23/23 - 0s - 7ms/step - loss: 60.7778 - val_loss: 93.7378
Epoch 70/100
23/23 - 0s - 7ms/step - loss: 59.1953 - val_loss: 93.3747
Epoch 71/100
23/23 - 0s - 7ms/step - loss: 57.3560 - val_loss: 91.5884
Epoch 72/100
23/23 - 0s - 7ms/step - loss: 55.9843 - val_loss: 89.5454
Epoch 73/100
23/23 - 0s - 7ms/step - loss: 54.1301 - val_loss: 93.6980
Epoch 74/100
23/23 - 0s - 7ms/step - loss: 51.7336 - val_loss: 91.2991
Epoch 75/100
23/23 - 0s - 7ms/step - loss: 49.9831 - val_loss: 91.4905
Epoch 76/100
23/23 - 0s - 7ms/step - loss: 48.8979 - val_loss: 88.9083
Epoch 77/100
23/23 - 0s - 7ms/step - loss: 47.4492 - val_loss: 95.5437
Epoch 78/100
23/23 - 0s - 7ms/step - loss: 46.4861 - val_loss: 89.0854
Epoch 79/100
23/23 - 0s - 7ms/step - loss: 44.9316 - val_loss: 96.2554
Epoch 80/100
23/23 - 0s - 7ms/step - loss: 44.2298 - val_loss: 89.8200
Epoch 81/100
23/23 - 0s - 7ms/step - loss: 43.8876 - val_loss: 92.9479
Epoch 82/100
23/23 - 0s - 7ms/step - loss: 42.6521 - val_loss: 92.7654
Epoch 83/100
23/23 - 0s - 7ms/step - loss: 42.0235 - val_loss: 93.3559
Epoch 84/100
23/23 - 0s - 7ms/step - loss: 41.1028 - val_loss: 100.7302
Epoch 85/100
23/23 - 0s - 7ms/step - loss: 41.6399 - val_loss: 97.3175
Epoch 86/100
23/23 - 0s - 7ms/step - loss: 40.2089 - val_loss: 88.7574
Epoch 87/100
23/23 - 0s - 7ms/step - loss: 39.8652 - val_loss: 102.6674
Epoch 88/100
23/23 - 0s - 6ms/step - loss: 38.5936 - val_loss: 101.3451
Epoch 89/100
23/23 - 0s - 7ms/step - loss: 38.1575 - val_loss: 102.3145
Epoch 90/100
23/23 - 0s - 7ms/step - loss: 37.7193 - val_loss: 96.5487
Epoch 91/100
23/23 - 0s - 7ms/step - loss: 38.0635 - val_loss: 101.8636
Epoch 92/100
23/23 - 0s - 7ms/step - loss: 37.3575 - val_loss: 109.8148
Epoch 93/100
23/23 - 0s - 7ms/step - loss: 36.4980 - val_loss: 103.1463
Epoch 94/100
23/23 - 0s - 7ms/step - loss: 36.1128 - val_loss: 102.1004
Epoch 95/100
23/23 - 0s - 7ms/step - loss: 35.7170 - val_loss: 113.1001
Epoch 96/100
23/23 - 0s - 7ms/step - loss: 35.3843 - val_loss: 102.3703
Epoch 97/100
23/23 - 0s - 7ms/step - loss: 35.0175 - val_loss: 107.6309
Epoch 98/100
23/23 - 0s - 7ms/step - loss: 35.3550 - val_loss: 113.5971
Epoch 99/100
23/23 - 0s - 6ms/step - loss: 34.1726 - val_loss: 108.3127
Epoch 100/100
23/23 - 0s - 7ms/step - loss: 33.9468 - val_loss: 106.1948

In [ ]:
# Write your code here

### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

<!--
## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2024-11-20  | 3.0  | Aman  |  Updated the library versions to current |
| 2020-09-21  | 2.0  | Srishti  |  Migrated Lab to Markdown and added to course repo in GitLab |



<hr>

## <h3 align="center"> © IBM Corporation. All rights reserved. <h3/>

## <h3 align="center"> &#169; IBM Corporation. All rights reserved. <h3/>